apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: proxy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Select an available port in range 30000-32767
  selector:
    app: nginx-proxy

