apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy-app
  namespace: argocd
spec:
  destination:
    namespace: proxy
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/prajwaldhone/ICA-3/tree/main/wordpress-gitops
    targetRevision: HEAD
    path: proxy/helm-chart
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
