apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      id: Co928109
      app: db
      env: dev
  template:
    metadata:
      labels:
        id: Co928109
        app: db
        env: dev
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6.4-focal
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Co928109
            - name: MYSQL_DATABASE
              value: Co928109
            - name: MYSQL_USER
              value: 3324_user
            - name: MYSQL_PASSWORD
              value: Co928109
