apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app
  namespace: wp
spec:
  replicas: 3
  selector:
    matchLabels:
      id: c0928743
      app: wp-app
      env: dev
  template:
    metadata:
      labels:
        id: c0928743
        app: wp-app
        env: dev
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: db-service.db.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: wp_user
            - name: WORDPRESS_DB_PASSWORD
              value: wp_pass
            - name: WORDPRESS_DB_NAME
              value: wp_db
          ports:
            - containerPort: 80
