apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      id: Co928109
      app: wp-app
      env: dev
  template:
    metadata:
      labels:
        id: Co928109
        app: wp-app
        env: dev
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: db-service.db.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: 3324_user
            - name: WORDPRESS_DB_PASSWORD
              value: Co928109
            - name: WORDPRESS_DB_NAME
              value: Co928109
